---
title: Colour a snowman
hero_image: images/banner.png
description: Learn how to colour in a 3D model of a snowman using Blender
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-01-28
steps:
- title: What you will make
- title: Colour the hat
- title: Colour an eye
  completion:
  - engaged
- title: Colour the eyes and buttons
- title: Colour the nose
  completion:
  - internal
- title: Challenge
  challenge: true
- title: What can you do now?
  completion:
  - external
  