---
title: स्नोमैन को रंग करें
hero_image: images/banner.png
description: सीखें कि Blender का उपयोग करके स्नोमैन के 3D मॉडल में रंग कैसे भरें।
theme: लाल #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: कला
technologies: blender
site_areas: परियोजनाएं
hardware: ''
software: blender
version: 4
last_tested: 2020-01-28
steps:
  - 
    title: भूमिका
  - 
    title: टोपी में रंग भरें
  - 
    title: एक आँख को रंग करें
  - 
    title: आँखों और बटनों को रंग करें
  - 
    title: नाक को रंग करें
  - 
    title: "चुनौती: शरीर पर रंग करें"
