---
title: Färbe einen Schneemann
hero_image: images/banner.png
description: Lerne, wie mit Blender ein 3D-Modell eines Schneemanns einfärbt
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-01-28
steps:
- title: Einleitung
  completion: engaged
- title: Färbe den Hut
- title: Färbe ein Auge
- title: Färbe die Augen und Knöpfe
- title: Färbe die Nase
  completion: internal
- title: 'Herausforderung: Färbe den Körper'
